// <auto-generated />
using System;
using AeroTech.Ancillary.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AeroTech.Ancillary.Persistence.Migrations
{
    [DbContext(typeof(AncillaryDbContext))]
    [Migration("20261008103942_V12Phase1NormalizedProvisionAndPricing")]
    partial class V12Phase1NormalizedProvisionAndPricing
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Ancillary")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryPricingAggregate.AncillaryPricing", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<int?>("FeeApplicationUnit")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<int?>("PricingUnit")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("SuspendedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("AncillaryProvisionId", "Version")
                        .IsUnique();

                    b.HasIndex(new[] { "AncillaryProvisionId", "Status" }, "IX_AncillaryPricings_OneActivePerProvision")
                        .IsUnique()
                        .HasFilter("[Status] = 2");

                    b.ToTable("AncillaryPricings", "Ancillary");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryPricingAggregate.Entities.AncillaryPricingLine", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int?>("AgeFromInclusive")
                        .HasColumnType("int");

                    b.Property<int?>("AgeToExclusive")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("AncillaryPricingId")
                        .HasColumnType("bigint");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PassengerTypeCode")
                        .HasColumnType("int");

                    b.Property<int?>("StationAirportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryPricingId");

                    b.ToTable("AncillaryPricingLines", "Ancillary");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.AncillaryProvision", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CoverageScope")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset?>("SalesDiscontinueAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("SalesEffectiveFrom")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<long>("ServiceDefinitionId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("SuspendedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ServiceDefinitionId");

                    b.HasIndex("Status");

                    b.HasIndex(new[] { "ServiceDefinitionId", "Sequence" }, "IX_AncillaryProvisions_ServiceDefinitionId_Sequence_Active")
                        .IsUnique()
                        .HasFilter("[Status] = 2");

                    b.ToTable("AncillaryProvisions", "Ancillary");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionAirFare", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AirFareId")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId", "AirFareId")
                        .IsUnique();

                    b.ToTable("ProvisionAirFares", "Ancillary");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionAirFareType", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("AirFareType")
                        .HasColumnType("int");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId", "AirFareType")
                        .IsUnique();

                    b.ToTable("ProvisionAirFareTypes", "Ancillary");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionAircraft", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("AircraftId")
                        .HasColumnType("int");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId", "AircraftId")
                        .IsUnique();

                    b.ToTable("ProvisionAircraft", "Ancillary");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionBlackoutPeriod", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId", "StartDate", "EndDate")
                        .IsUnique();

                    b.ToTable("ProvisionBlackoutPeriods", "Ancillary");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionCabinClass", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<int>("CabinClassId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId", "CabinClassId")
                        .IsUnique();

                    b.ToTable("ProvisionCabinClasses", "Ancillary");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionCustomer", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId", "CustomerId")
                        .IsUnique();

                    b.ToTable("ProvisionCustomers", "Ancillary");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionCustomerType", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<int>("CustomerType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId", "CustomerType")
                        .IsUnique();

                    b.ToTable("ProvisionCustomerTypes", "Ancillary");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionDayTimeRestriction", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("Effect")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId", "DayOfWeek", "StartTime", "EndTime", "Effect")
                        .IsUnique()
                        .HasFilter("[StartTime] IS NOT NULL AND [EndTime] IS NOT NULL");

                    b.ToTable("ProvisionDayTimeRestrictions", "Ancillary");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionDestinationAirport", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("AirportId")
                        .HasColumnType("int");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId", "AirportId")
                        .IsUnique();

                    b.ToTable("ProvisionDestinationAirports", "Ancillary");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionFareBasis", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<string>("FareBasisCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId", "FareBasisCode")
                        .IsUnique();

                    b.ToTable("ProvisionFareBases", "Ancillary");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionFareFamily", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<long>("FareFamilyId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId", "FareFamilyId")
                        .IsUnique();

                    b.ToTable("ProvisionFareFamilies", "Ancillary");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionFlight", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<long>("FlightId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId", "FlightId")
                        .IsUnique();

                    b.ToTable("ProvisionFlights", "Ancillary");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionFlightNumber", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId", "FlightNumber")
                        .IsUnique();

                    b.ToTable("ProvisionFlightNumbers", "Ancillary");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionMarketingAirline", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("AirlineId")
                        .HasColumnType("int");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId", "AirlineId")
                        .IsUnique();

                    b.ToTable("ProvisionMarketingAirlines", "Ancillary");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionOperatingAirline", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("AirlineId")
                        .HasColumnType("int");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId", "AirlineId")
                        .IsUnique();

                    b.ToTable("ProvisionOperatingAirlines", "Ancillary");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionOriginAirport", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("AirportId")
                        .HasColumnType("int");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId", "AirportId")
                        .IsUnique();

                    b.ToTable("ProvisionOriginAirports", "Ancillary");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionPassengerType", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<int>("PassengerTypeCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId", "PassengerTypeCode")
                        .IsUnique();

                    b.ToTable("ProvisionPassengerTypes", "Ancillary");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionPointOfSale", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("PointOfSaleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId", "PointOfSaleId")
                        .IsUnique();

                    b.ToTable("ProvisionPointsOfSale", "Ancillary");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionRbd", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("RbdId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId", "RbdId")
                        .IsUnique();

                    b.ToTable("ProvisionRbds", "Ancillary");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionRoutePair", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<int>("DestinationAirportId")
                        .HasColumnType("int");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<int>("OriginAirportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId", "OriginAirportId", "DestinationAirportId")
                        .IsUnique();

                    b.ToTable("ProvisionRoutePairs", "Ancillary");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionSeasonalPeriod", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId", "StartDate", "EndDate")
                        .IsUnique();

                    b.ToTable("ProvisionSeasonalPeriods", "Ancillary");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionSeatCharacteristic", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<string>("CharacteristicCode")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId", "CharacteristicCode")
                        .IsUnique();

                    b.ToTable("ProvisionSeatCharacteristics", "Ancillary");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionSeatNumber", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId", "SeatNumber")
                        .IsUnique();

                    b.ToTable("ProvisionSeatNumbers", "Ancillary");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionTravelDate", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("TravelDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId", "TravelDate")
                        .IsUnique();

                    b.ToTable("ProvisionTravelDates", "Ancillary");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionViaAirport", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("AirportId")
                        .HasColumnType("int");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId", "AirportId")
                        .IsUnique();

                    b.ToTable("ProvisionViaAirports", "Ancillary");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryReservationAggregate.AncillaryReservation", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("RequestedExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("OrderId");

                    b.ToTable("AncillaryReservations", "Ancillary");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryReservationAggregate.Entities.AncillaryReservationUnit", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryReservationId")
                        .HasColumnType("bigint");

                    b.Property<string>("CancellationReasonCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CoverageScope")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("CoveredFlightIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderServiceId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProviderUnitRef")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("ProvisionId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<long>("ServiceDefinitionId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long?>("StockPoolId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TravellerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryReservationId");

                    b.HasIndex("OrderServiceId");

                    b.ToTable("AncillaryReservationUnits", "Ancillary");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryServiceDefinitionAggregate.AncillaryServiceDefinition", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CommercialName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description1Code")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Description2Code")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("GroupCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<int>("OwnerAirlineId")
                        .HasColumnType("int");

                    b.Property<int?>("PricingUnit")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateOnly?>("SalesDiscontinueOn")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("SalesEffectiveFrom")
                        .HasColumnType("date");

                    b.Property<string>("ServiceDefinitionRef")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ServiceSubCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("ServiceTypeCode")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SubCodeSource")
                        .HasColumnType("int");

                    b.Property<string>("SubGroupCode")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<long>("SupplierId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("SuspendedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("SupplierId");

                    b.HasIndex("OwnerAirlineId", "ServiceDefinitionRef", "Version")
                        .IsUnique();

                    b.HasIndex(new[] { "OwnerAirlineId", "ServiceDefinitionRef" }, "IX_AncillaryServiceDefinitions_OwnerAirlineId_Ref_Active")
                        .IsUnique()
                        .HasFilter("[Status] = 2");

                    b.ToTable("AncillaryServiceDefinitions", "Ancillary");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.SupplierAggregate.Supplier", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("FulfillmentKind")
                        .HasColumnType("int");

                    b.Property<string>("FulfillmentProviderKey")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OwnerAirlineId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Suppliers", "Ancillary");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Persistence.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Consumer")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("ReceivedOn")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("MessageId", "Consumer");

                    b.HasIndex("ReceivedOn");

                    b.ToTable("InboxMessages", "dbo");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ProcessedOn")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOn");

                    b.ToTable("OutboxMessages", "dbo");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryPricingAggregate.AncillaryPricing", b =>
                {
                    b.HasOne("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.AncillaryProvision", null)
                        .WithMany()
                        .HasForeignKey("AncillaryProvisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryPricingAggregate.Entities.AncillaryPricingLine", b =>
                {
                    b.HasOne("AeroTech.Ancillary.Domain.AncillaryPricingAggregate.AncillaryPricing", null)
                        .WithMany("PriceLines")
                        .HasForeignKey("AncillaryPricingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.AncillaryProvision", b =>
                {
                    b.OwnsOne("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.ValueObjects.AdvancePurchaseCriteria", "AdvancePurchase", b1 =>
                        {
                            b1.Property<long>("AncillaryProvisionId")
                                .HasColumnType("bigint");

                            b1.Property<int>("Period")
                                .HasColumnType("int")
                                .HasColumnName("AdvancePurchasePeriod");

                            b1.Property<int>("Unit")
                                .HasColumnType("int")
                                .HasColumnName("AdvancePurchaseUnit");

                            b1.HasKey("AncillaryProvisionId");

                            b1.ToTable("AncillaryProvisions", "Ancillary");

                            b1.WithOwner()
                                .HasForeignKey("AncillaryProvisionId");
                        });

                    b.OwnsOne("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.ValueObjects.AvailabilityDefinition", "Availability", b1 =>
                        {
                            b1.Property<long>("AncillaryProvisionId")
                                .HasColumnType("bigint");

                            b1.Property<bool>("MustCheckAvailability")
                                .HasColumnType("bit")
                                .HasColumnName("MustCheckAvailability");

                            b1.HasKey("AncillaryProvisionId");

                            b1.ToTable("AncillaryProvisions", "Ancillary");

                            b1.WithOwner()
                                .HasForeignKey("AncillaryProvisionId");
                        });

                    b.OwnsOne("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.ValueObjects.CommercialOutcome", "Outcome", b1 =>
                        {
                            b1.Property<long>("AncillaryProvisionId")
                                .HasColumnType("bigint");

                            b1.Property<bool>("BookingRequired")
                                .HasColumnType("bit")
                                .HasColumnName("BookingRequired");

                            b1.Property<int>("Disposition")
                                .HasColumnType("int")
                                .HasColumnName("Disposition");

                            b1.Property<bool>("DocumentRequired")
                                .HasColumnType("bit")
                                .HasColumnName("DocumentRequired");

                            b1.HasKey("AncillaryProvisionId");

                            b1.ToTable("AncillaryProvisions", "Ancillary");

                            b1.WithOwner()
                                .HasForeignKey("AncillaryProvisionId");
                        });

                    b.OwnsOne("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.ValueObjects.FulfillmentDefinition", "Fulfillment", b1 =>
                        {
                            b1.Property<long>("AncillaryProvisionId")
                                .HasColumnType("bigint");

                            b1.Property<string>("FulfillmentProviderKey")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("FulfillmentProviderKey");

                            b1.HasKey("AncillaryProvisionId");

                            b1.ToTable("AncillaryProvisions", "Ancillary");

                            b1.WithOwner()
                                .HasForeignKey("AncillaryProvisionId");
                        });

                    b.OwnsOne("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.ValueObjects.ProvisionApplication", "Application", b1 =>
                        {
                            b1.Property<long>("AncillaryProvisionId")
                                .HasColumnType("bigint");

                            b1.Property<int>("Type")
                                .HasColumnType("int")
                                .HasColumnName("ApplicationType");

                            b1.HasKey("AncillaryProvisionId");

                            b1.ToTable("AncillaryProvisions", "Ancillary");

                            b1.WithOwner()
                                .HasForeignKey("AncillaryProvisionId");

                            b1.OwnsOne("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.ValueObjects.BaggageApplication", "Baggage", b2 =>
                                {
                                    b2.Property<long>("ProvisionApplicationAncillaryProvisionId")
                                        .HasColumnType("bigint");

                                    b2.Property<int?>("FirstExcessPiece")
                                        .HasColumnType("int")
                                        .HasColumnName("BaggageFirstExcessPiece");

                                    b2.Property<int?>("FreePieces")
                                        .HasColumnType("int")
                                        .HasColumnName("BaggageFreePieces");

                                    b2.Property<int?>("LastExcessPiece")
                                        .HasColumnType("int")
                                        .HasColumnName("BaggageLastExcessPiece");

                                    b2.Property<int>("PurchaseApplication")
                                        .HasColumnType("int")
                                        .HasColumnName("BaggagePurchaseApplication");

                                    b2.Property<int?>("RuleDeference")
                                        .HasColumnType("int")
                                        .HasColumnName("BaggageRuleDeference");

                                    b2.Property<int?>("TravelApplication")
                                        .HasColumnType("int")
                                        .HasColumnName("BaggageTravelApplication");

                                    b2.Property<decimal?>("Weight")
                                        .HasPrecision(9, 2)
                                        .HasColumnType("decimal(9,2)")
                                        .HasColumnName("BaggageWeight");

                                    b2.Property<int>("WeightUnit")
                                        .HasColumnType("int")
                                        .HasColumnName("BaggageWeightUnit");

                                    b2.HasKey("ProvisionApplicationAncillaryProvisionId");

                                    b2.ToTable("AncillaryProvisions", "Ancillary");

                                    b2.WithOwner()
                                        .HasForeignKey("ProvisionApplicationAncillaryProvisionId");
                                });

                            b1.Navigation("Baggage");
                        });

                    b.OwnsOne("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.ValueObjects.QuantityRule", "Quantity", b1 =>
                        {
                            b1.Property<long>("AncillaryProvisionId")
                                .HasColumnType("bigint");

                            b1.Property<int>("MaxQuantity")
                                .HasColumnType("int")
                                .HasColumnName("MaxQuantity");

                            b1.Property<int>("MinQuantity")
                                .HasColumnType("int")
                                .HasColumnName("MinQuantity");

                            b1.Property<int>("Unit")
                                .HasColumnType("int")
                                .HasColumnName("QuantityUnit");

                            b1.HasKey("AncillaryProvisionId");

                            b1.ToTable("AncillaryProvisions", "Ancillary");

                            b1.WithOwner()
                                .HasForeignKey("AncillaryProvisionId");
                        });

                    b.OwnsOne("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.ValueObjects.SettlementDefinition", "Settlement", b1 =>
                        {
                            b1.Property<long>("AncillaryProvisionId")
                                .HasColumnType("bigint");

                            b1.Property<bool>("Commissionable")
                                .HasColumnType("bit")
                                .HasColumnName("Commissionable");

                            b1.Property<int?>("FormOfRefund")
                                .HasColumnType("int")
                                .HasColumnName("FormOfRefund");

                            b1.Property<bool>("InterlineSettlement")
                                .HasColumnType("bit")
                                .HasColumnName("InterlineSettlement");

                            b1.Property<int>("ReissueRefund")
                                .HasColumnType("int")
                                .HasColumnName("ReissueRefund");

                            b1.HasKey("AncillaryProvisionId");

                            b1.ToTable("AncillaryProvisions", "Ancillary");

                            b1.WithOwner()
                                .HasForeignKey("AncillaryProvisionId");
                        });

                    b.Navigation("AdvancePurchase");

                    b.Navigation("Application")
                        .IsRequired();

                    b.Navigation("Availability")
                        .IsRequired();

                    b.Navigation("Fulfillment")
                        .IsRequired();

                    b.Navigation("Outcome")
                        .IsRequired();

                    b.Navigation("Quantity")
                        .IsRequired();

                    b.Navigation("Settlement")
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionAirFare", b =>
                {
                    b.HasOne("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.AncillaryProvision", null)
                        .WithMany("AirFares")
                        .HasForeignKey("AncillaryProvisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionAirFareType", b =>
                {
                    b.HasOne("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.AncillaryProvision", null)
                        .WithMany("AirFareTypes")
                        .HasForeignKey("AncillaryProvisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionAircraft", b =>
                {
                    b.HasOne("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.AncillaryProvision", null)
                        .WithMany("Aircraft")
                        .HasForeignKey("AncillaryProvisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionBlackoutPeriod", b =>
                {
                    b.HasOne("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.AncillaryProvision", null)
                        .WithMany("BlackoutPeriods")
                        .HasForeignKey("AncillaryProvisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionCabinClass", b =>
                {
                    b.HasOne("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.AncillaryProvision", null)
                        .WithMany("CabinClasses")
                        .HasForeignKey("AncillaryProvisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionCustomer", b =>
                {
                    b.HasOne("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.AncillaryProvision", null)
                        .WithMany("Customers")
                        .HasForeignKey("AncillaryProvisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionCustomerType", b =>
                {
                    b.HasOne("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.AncillaryProvision", null)
                        .WithMany("CustomerTypes")
                        .HasForeignKey("AncillaryProvisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionDayTimeRestriction", b =>
                {
                    b.HasOne("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.AncillaryProvision", null)
                        .WithMany("DayTimeRestrictions")
                        .HasForeignKey("AncillaryProvisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionDestinationAirport", b =>
                {
                    b.HasOne("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.AncillaryProvision", null)
                        .WithMany("DestinationAirports")
                        .HasForeignKey("AncillaryProvisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionFareBasis", b =>
                {
                    b.HasOne("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.AncillaryProvision", null)
                        .WithMany("FareBases")
                        .HasForeignKey("AncillaryProvisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionFareFamily", b =>
                {
                    b.HasOne("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.AncillaryProvision", null)
                        .WithMany("FareFamilies")
                        .HasForeignKey("AncillaryProvisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionFlight", b =>
                {
                    b.HasOne("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.AncillaryProvision", null)
                        .WithMany("Flights")
                        .HasForeignKey("AncillaryProvisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionFlightNumber", b =>
                {
                    b.HasOne("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.AncillaryProvision", null)
                        .WithMany("FlightNumbers")
                        .HasForeignKey("AncillaryProvisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionMarketingAirline", b =>
                {
                    b.HasOne("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.AncillaryProvision", null)
                        .WithMany("MarketingAirlines")
                        .HasForeignKey("AncillaryProvisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionOperatingAirline", b =>
                {
                    b.HasOne("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.AncillaryProvision", null)
                        .WithMany("OperatingAirlines")
                        .HasForeignKey("AncillaryProvisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionOriginAirport", b =>
                {
                    b.HasOne("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.AncillaryProvision", null)
                        .WithMany("OriginAirports")
                        .HasForeignKey("AncillaryProvisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionPassengerType", b =>
                {
                    b.HasOne("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.AncillaryProvision", null)
                        .WithMany("PassengerTypes")
                        .HasForeignKey("AncillaryProvisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionPointOfSale", b =>
                {
                    b.HasOne("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.AncillaryProvision", null)
                        .WithMany("PointsOfSale")
                        .HasForeignKey("AncillaryProvisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionRbd", b =>
                {
                    b.HasOne("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.AncillaryProvision", null)
                        .WithMany("Rbds")
                        .HasForeignKey("AncillaryProvisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionRoutePair", b =>
                {
                    b.HasOne("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.AncillaryProvision", null)
                        .WithMany("RoutePairs")
                        .HasForeignKey("AncillaryProvisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionSeasonalPeriod", b =>
                {
                    b.HasOne("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.AncillaryProvision", null)
                        .WithMany("SeasonalPeriods")
                        .HasForeignKey("AncillaryProvisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionSeatCharacteristic", b =>
                {
                    b.HasOne("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.AncillaryProvision", null)
                        .WithMany("SeatCharacteristics")
                        .HasForeignKey("AncillaryProvisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionSeatNumber", b =>
                {
                    b.HasOne("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.AncillaryProvision", null)
                        .WithMany("SeatNumbers")
                        .HasForeignKey("AncillaryProvisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionTravelDate", b =>
                {
                    b.HasOne("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.AncillaryProvision", null)
                        .WithMany("TravelDates")
                        .HasForeignKey("AncillaryProvisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionViaAirport", b =>
                {
                    b.HasOne("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.AncillaryProvision", null)
                        .WithMany("ViaAirports")
                        .HasForeignKey("AncillaryProvisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryReservationAggregate.Entities.AncillaryReservationUnit", b =>
                {
                    b.HasOne("AeroTech.Ancillary.Domain.AncillaryReservationAggregate.AncillaryReservation", null)
                        .WithMany("Units")
                        .HasForeignKey("AncillaryReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryServiceDefinitionAggregate.AncillaryServiceDefinition", b =>
                {
                    b.OwnsOne("AeroTech.Ancillary.Domain.AncillaryServiceDefinitionAggregate.ValueObjects.BookingDefinition", "Booking", b1 =>
                        {
                            b1.Property<long>("AncillaryServiceDefinitionId")
                                .HasColumnType("bigint");

                            b1.Property<int>("Method")
                                .HasColumnType("int")
                                .HasColumnName("BookingMethod");

                            b1.Property<string>("SsimCode")
                                .HasMaxLength(4)
                                .HasColumnType("nvarchar(4)")
                                .HasColumnName("BookingSsimCode");

                            b1.Property<string>("SsrCode")
                                .HasMaxLength(4)
                                .HasColumnType("nvarchar(4)")
                                .HasColumnName("BookingSsrCode");

                            b1.HasKey("AncillaryServiceDefinitionId");

                            b1.ToTable("AncillaryServiceDefinitions", "Ancillary");

                            b1.WithOwner()
                                .HasForeignKey("AncillaryServiceDefinitionId");
                        });

                    b.OwnsOne("AeroTech.Ancillary.Domain.AncillaryServiceDefinitionAggregate.ValueObjects.DocumentDefinition", "Document", b1 =>
                        {
                            b1.Property<long>("AncillaryServiceDefinitionId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Rfic")
                                .HasMaxLength(1)
                                .HasColumnType("nvarchar(1)")
                                .HasColumnName("DocumentRfic");

                            b1.Property<string>("Rfisc")
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("DocumentRfisc");

                            b1.Property<int>("Type")
                                .HasColumnType("int")
                                .HasColumnName("DocumentType");

                            b1.HasKey("AncillaryServiceDefinitionId");

                            b1.ToTable("AncillaryServiceDefinitions", "Ancillary");

                            b1.WithOwner()
                                .HasForeignKey("AncillaryServiceDefinitionId");
                        });

                    b.Navigation("Booking")
                        .IsRequired();

                    b.Navigation("Document")
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryPricingAggregate.AncillaryPricing", b =>
                {
                    b.Navigation("PriceLines");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.AncillaryProvision", b =>
                {
                    b.Navigation("AirFareTypes");

                    b.Navigation("AirFares");

                    b.Navigation("Aircraft");

                    b.Navigation("BlackoutPeriods");

                    b.Navigation("CabinClasses");

                    b.Navigation("CustomerTypes");

                    b.Navigation("Customers");

                    b.Navigation("DayTimeRestrictions");

                    b.Navigation("DestinationAirports");

                    b.Navigation("FareBases");

                    b.Navigation("FareFamilies");

                    b.Navigation("FlightNumbers");

                    b.Navigation("Flights");

                    b.Navigation("MarketingAirlines");

                    b.Navigation("OperatingAirlines");

                    b.Navigation("OriginAirports");

                    b.Navigation("PassengerTypes");

                    b.Navigation("PointsOfSale");

                    b.Navigation("Rbds");

                    b.Navigation("RoutePairs");

                    b.Navigation("SeasonalPeriods");

                    b.Navigation("SeatCharacteristics");

                    b.Navigation("SeatNumbers");

                    b.Navigation("TravelDates");

                    b.Navigation("ViaAirports");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryReservationAggregate.AncillaryReservation", b =>
                {
                    b.Navigation("Units");
                });
#pragma warning restore 612, 618
        }
    }
}
