// <auto-generated />
using System;
using AeroTech.Ancillary.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AeroTech.Ancillary.Persistence.Migrations
{
    [DbContext(typeof(AncillaryDbContext))]
    partial class AncillaryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Ancillary")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.AncillaryProvision", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ApplicationType")
                        .HasColumnType("int");

                    b.Property<int>("CoverageScope")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset?>("SalesDiscontinueAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("SalesEffectiveFrom")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<long>("ServiceDefinitionId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("SuspendedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ServiceDefinitionId");

                    b.HasIndex("Status");

                    b.HasIndex(new[] { "ServiceDefinitionId", "Sequence" }, "IX_AncillaryProvisions_ServiceDefinitionId_Sequence_Active")
                        .IsUnique()
                        .HasFilter("[Status] = 2");

                    b.ToTable("AncillaryProvisions", "Ancillary");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionPriceLine", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("UnitAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("ProvisionPriceLines", "Ancillary");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryReservationAggregate.AncillaryReservation", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("RequestedExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("OrderId");

                    b.ToTable("AncillaryReservations", "Ancillary");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryReservationAggregate.Entities.AncillaryReservationUnit", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryReservationId")
                        .HasColumnType("bigint");

                    b.Property<string>("CancellationReasonCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CoverageScope")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("CoveredFlightIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderServiceId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProviderUnitRef")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("ProvisionId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<long>("ServiceDefinitionId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long?>("StockPoolId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TravellerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryReservationId");

                    b.HasIndex("OrderServiceId");

                    b.ToTable("AncillaryReservationUnits", "Ancillary");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryServiceDefinitionAggregate.AncillaryServiceDefinition", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CommercialName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description1Code")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Description2Code")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("GroupCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<int>("OwnerAirlineId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateOnly?>("SalesDiscontinueOn")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("SalesEffectiveFrom")
                        .HasColumnType("date");

                    b.Property<string>("ServiceDefinitionRef")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ServiceSubCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("ServiceTypeCode")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SubCodeSource")
                        .HasColumnType("int");

                    b.Property<string>("SubGroupCode")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<long>("SupplierId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("SuspendedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("SupplierId");

                    b.HasIndex("OwnerAirlineId", "ServiceDefinitionRef", "Version")
                        .IsUnique();

                    b.HasIndex(new[] { "OwnerAirlineId", "ServiceDefinitionRef" }, "IX_AncillaryServiceDefinitions_OwnerAirlineId_Ref_Active")
                        .IsUnique()
                        .HasFilter("[Status] = 2");

                    b.ToTable("AncillaryServiceDefinitions", "Ancillary");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.SupplierAggregate.Supplier", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("FulfillmentKind")
                        .HasColumnType("int");

                    b.Property<string>("FulfillmentProviderKey")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OwnerAirlineId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Suppliers", "Ancillary");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Persistence.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Consumer")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("ReceivedOn")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("MessageId", "Consumer");

                    b.HasIndex("ReceivedOn");

                    b.ToTable("InboxMessages", "dbo");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ProcessedOn")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOn");

                    b.ToTable("OutboxMessages", "dbo");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.AncillaryProvision", b =>
                {
                    b.OwnsOne("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.ValueObjects.AvailabilityDefinition", "Availability", b1 =>
                        {
                            b1.Property<long>("AncillaryProvisionId")
                                .HasColumnType("bigint");

                            b1.Property<bool>("MustCheckAvailability")
                                .HasColumnType("bit")
                                .HasColumnName("MustCheckAvailability");

                            b1.HasKey("AncillaryProvisionId");

                            b1.ToTable("AncillaryProvisions", "Ancillary");

                            b1.WithOwner()
                                .HasForeignKey("AncillaryProvisionId");
                        });

                    b.OwnsOne("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.ValueObjects.CommercialOutcome", "Outcome", b1 =>
                        {
                            b1.Property<long>("AncillaryProvisionId")
                                .HasColumnType("bigint");

                            b1.Property<bool>("BookingRequired")
                                .HasColumnType("bit")
                                .HasColumnName("BookingRequired");

                            b1.Property<int>("Disposition")
                                .HasColumnType("int")
                                .HasColumnName("Disposition");

                            b1.Property<bool>("DocumentRequired")
                                .HasColumnType("bit")
                                .HasColumnName("DocumentRequired");

                            b1.HasKey("AncillaryProvisionId");

                            b1.ToTable("AncillaryProvisions", "Ancillary");

                            b1.WithOwner()
                                .HasForeignKey("AncillaryProvisionId");
                        });

                    b.OwnsOne("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.ValueObjects.FeeDefinition", "Fee", b1 =>
                        {
                            b1.Property<long>("AncillaryProvisionId")
                                .HasColumnType("bigint");

                            b1.Property<int>("ApplicationUnit")
                                .HasColumnType("int")
                                .HasColumnName("FeeApplicationUnit");

                            b1.Property<int>("CurrencyId")
                                .HasColumnType("int")
                                .HasColumnName("FeeCurrencyId");

                            b1.HasKey("AncillaryProvisionId");

                            b1.ToTable("AncillaryProvisions", "Ancillary");

                            b1.WithOwner()
                                .HasForeignKey("AncillaryProvisionId");
                        });

                    b.OwnsOne("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.ValueObjects.FulfillmentDefinition", "Fulfillment", b1 =>
                        {
                            b1.Property<long>("AncillaryProvisionId")
                                .HasColumnType("bigint");

                            b1.Property<string>("FulfillmentProviderKey")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("FulfillmentProviderKey");

                            b1.HasKey("AncillaryProvisionId");

                            b1.ToTable("AncillaryProvisions", "Ancillary");

                            b1.WithOwner()
                                .HasForeignKey("AncillaryProvisionId");
                        });

                    b.OwnsOne("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.ValueObjects.QuantityRule", "Quantity", b1 =>
                        {
                            b1.Property<long>("AncillaryProvisionId")
                                .HasColumnType("bigint");

                            b1.Property<int>("MaxQuantity")
                                .HasColumnType("int")
                                .HasColumnName("MaxQuantity");

                            b1.Property<int>("MinQuantity")
                                .HasColumnType("int")
                                .HasColumnName("MinQuantity");

                            b1.Property<int>("Unit")
                                .HasColumnType("int")
                                .HasColumnName("QuantityUnit");

                            b1.HasKey("AncillaryProvisionId");

                            b1.ToTable("AncillaryProvisions", "Ancillary");

                            b1.WithOwner()
                                .HasForeignKey("AncillaryProvisionId");
                        });

                    b.OwnsOne("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.ValueObjects.SettlementDefinition", "Settlement", b1 =>
                        {
                            b1.Property<long>("AncillaryProvisionId")
                                .HasColumnType("bigint");

                            b1.Property<bool>("Commissionable")
                                .HasColumnType("bit")
                                .HasColumnName("Commissionable");

                            b1.Property<int?>("FormOfRefund")
                                .HasColumnType("int")
                                .HasColumnName("FormOfRefund");

                            b1.Property<bool>("InterlineSettlement")
                                .HasColumnType("bit")
                                .HasColumnName("InterlineSettlement");

                            b1.Property<int>("ReissueRefund")
                                .HasColumnType("int")
                                .HasColumnName("ReissueRefund");

                            b1.HasKey("AncillaryProvisionId");

                            b1.ToTable("AncillaryProvisions", "Ancillary");

                            b1.WithOwner()
                                .HasForeignKey("AncillaryProvisionId");
                        });

                    b.Navigation("Availability")
                        .IsRequired();

                    b.Navigation("Fee");

                    b.Navigation("Fulfillment")
                        .IsRequired();

                    b.Navigation("Outcome")
                        .IsRequired();

                    b.Navigation("Quantity")
                        .IsRequired();

                    b.Navigation("Settlement")
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.Entities.ProvisionPriceLine", b =>
                {
                    b.HasOne("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.AncillaryProvision", null)
                        .WithMany("PriceLines")
                        .HasForeignKey("AncillaryProvisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryReservationAggregate.Entities.AncillaryReservationUnit", b =>
                {
                    b.HasOne("AeroTech.Ancillary.Domain.AncillaryReservationAggregate.AncillaryReservation", null)
                        .WithMany("Units")
                        .HasForeignKey("AncillaryReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryServiceDefinitionAggregate.AncillaryServiceDefinition", b =>
                {
                    b.OwnsOne("AeroTech.Ancillary.Domain.AncillaryServiceDefinitionAggregate.ValueObjects.BookingDefinition", "Booking", b1 =>
                        {
                            b1.Property<long>("AncillaryServiceDefinitionId")
                                .HasColumnType("bigint");

                            b1.Property<int>("Method")
                                .HasColumnType("int")
                                .HasColumnName("BookingMethod");

                            b1.Property<string>("SsimCode")
                                .HasMaxLength(4)
                                .HasColumnType("nvarchar(4)")
                                .HasColumnName("BookingSsimCode");

                            b1.Property<string>("SsrCode")
                                .HasMaxLength(4)
                                .HasColumnType("nvarchar(4)")
                                .HasColumnName("BookingSsrCode");

                            b1.HasKey("AncillaryServiceDefinitionId");

                            b1.ToTable("AncillaryServiceDefinitions", "Ancillary");

                            b1.WithOwner()
                                .HasForeignKey("AncillaryServiceDefinitionId");
                        });

                    b.OwnsOne("AeroTech.Ancillary.Domain.AncillaryServiceDefinitionAggregate.ValueObjects.DocumentDefinition", "Document", b1 =>
                        {
                            b1.Property<long>("AncillaryServiceDefinitionId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Rfic")
                                .HasMaxLength(1)
                                .HasColumnType("nvarchar(1)")
                                .HasColumnName("DocumentRfic");

                            b1.Property<string>("Rfisc")
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("DocumentRfisc");

                            b1.Property<int>("Type")
                                .HasColumnType("int")
                                .HasColumnName("DocumentType");

                            b1.HasKey("AncillaryServiceDefinitionId");

                            b1.ToTable("AncillaryServiceDefinitions", "Ancillary");

                            b1.WithOwner()
                                .HasForeignKey("AncillaryServiceDefinitionId");
                        });

                    b.Navigation("Booking")
                        .IsRequired();

                    b.Navigation("Document")
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProvisionAggregate.AncillaryProvision", b =>
                {
                    b.Navigation("PriceLines");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryReservationAggregate.AncillaryReservation", b =>
                {
                    b.Navigation("Units");
                });
#pragma warning restore 612, 618
        }
    }
}
