// <auto-generated />
using System;
using AeroTech.Ancillary.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AeroTech.Ancillary.Persistence.Migrations
{
    [DbContext(typeof(AncillaryDbContext))]
    partial class AncillaryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Ancillary")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryPriceRuleAggregate.AncillaryPriceRule", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<int>("OwnerAirlineId")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("ProductRef")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset?>("SalesFrom")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("SalesTo")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("TravelFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("TravelTo")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId", "Status");

                    b.HasIndex("OwnerAirlineId", "ProductRef", "CurrencyId", "Priority")
                        .IsUnique()
                        .HasFilter("[Status] = 2");

                    b.ToTable("AncillaryPriceRules", "Ancillary");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryPriceRuleAggregate.Entities.PriceLine", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("AncillaryPriceRuleId")
                        .HasColumnType("bigint");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryPriceRuleId");

                    b.ToTable("PriceLines", "Ancillary");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProductAggregate.AncillaryProduct", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("InventoryControl")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OwnerAirlineId")
                        .HasColumnType("int");

                    b.Property<string>("ProductRef")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SalesScope")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("OwnerAirlineId", "ProductRef", "Version")
                        .IsUnique();

                    b.HasIndex(new[] { "OwnerAirlineId", "ProductRef" }, "IX_AncillaryProducts_OwnerAirlineId_ProductRef_Draft")
                        .IsUnique()
                        .HasFilter("[Status] = 1");

                    b.HasIndex(new[] { "OwnerAirlineId", "ProductRef" }, "IX_AncillaryProducts_OwnerAirlineId_ProductRef_Offered")
                        .IsUnique()
                        .HasFilter("[Status] IN (2, 3)");

                    b.ToTable("AncillaryProducts", "Ancillary");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.ServiceSubCodeAggregate.ServiceSubCode", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("CommercialName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description1Code")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Description2Code")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("GroupCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<int>("OwnerAirlineId")
                        .HasColumnType("int");

                    b.Property<string>("Rfic")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SubGroupCode")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerAirlineId", "Code")
                        .IsUnique();

                    b.ToTable("ServiceSubCodes", "Ancillary");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Persistence.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Consumer")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("ReceivedOn")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("MessageId", "Consumer");

                    b.HasIndex("ReceivedOn");

                    b.ToTable("InboxMessages", "dbo");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ProcessedOn")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOn");

                    b.ToTable("OutboxMessages", "dbo");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryPriceRuleAggregate.AncillaryPriceRule", b =>
                {
                    b.OwnsOne("AeroTech.Ancillary.Domain.AncillaryPriceRuleAggregate.ValueObjects.PriceRuleConditions", "Conditions", b1 =>
                        {
                            b1.Property<long>("AncillaryPriceRuleId")
                                .HasColumnType("bigint");

                            b1.PrimitiveCollection<string>("DestinationAirportIds")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("DestinationAirportIds");

                            b1.PrimitiveCollection<string>("OriginAirportIds")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("OriginAirportIds");

                            b1.PrimitiveCollection<string>("PassengerTypes")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PassengerTypes");

                            b1.HasKey("AncillaryPriceRuleId");

                            b1.ToTable("AncillaryPriceRules", "Ancillary");

                            b1.WithOwner()
                                .HasForeignKey("AncillaryPriceRuleId");
                        });

                    b.Navigation("Conditions")
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryPriceRuleAggregate.Entities.PriceLine", b =>
                {
                    b.HasOne("AeroTech.Ancillary.Domain.AncillaryPriceRuleAggregate.AncillaryPriceRule", null)
                        .WithMany("Lines")
                        .HasForeignKey("AncillaryPriceRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryProductAggregate.AncillaryProduct", b =>
                {
                    b.OwnsOne("AeroTech.Ancillary.Domain.AncillaryProductAggregate.ValueObjects.BaggageDetail", "Baggage", b1 =>
                        {
                            b1.Property<long>("AncillaryProductId")
                                .HasColumnType("bigint");

                            b1.Property<int?>("Pieces")
                                .HasColumnType("int")
                                .HasColumnName("BaggagePieces");

                            b1.Property<decimal?>("Weight")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("BaggageWeight");

                            b1.Property<int?>("WeightUnit")
                                .HasColumnType("int")
                                .HasColumnName("BaggageWeightUnit");

                            b1.HasKey("AncillaryProductId");

                            b1.ToTable("AncillaryProducts", "Ancillary");

                            b1.WithOwner()
                                .HasForeignKey("AncillaryProductId");
                        });

                    b.OwnsOne("AeroTech.Ancillary.Domain.AncillaryProductAggregate.ValueObjects.DocumentPolicy", "Document", b1 =>
                        {
                            b1.Property<long>("AncillaryProductId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Rfic")
                                .HasMaxLength(1)
                                .HasColumnType("nvarchar(1)")
                                .HasColumnName("Rfic");

                            b1.Property<string>("Rfisc")
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("Rfisc");

                            b1.Property<int>("Type")
                                .HasColumnType("int")
                                .HasColumnName("DocumentType");

                            b1.HasKey("AncillaryProductId");

                            b1.ToTable("AncillaryProducts", "Ancillary");

                            b1.WithOwner()
                                .HasForeignKey("AncillaryProductId");
                        });

                    b.OwnsOne("AeroTech.Ancillary.Domain.AncillaryProductAggregate.ValueObjects.IndustryCodes", "Codes", b1 =>
                        {
                            b1.Property<long>("AncillaryProductId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Description1Code")
                                .HasMaxLength(2)
                                .HasColumnType("nvarchar(2)")
                                .HasColumnName("Description1Code");

                            b1.Property<string>("Description2Code")
                                .HasMaxLength(2)
                                .HasColumnType("nvarchar(2)")
                                .HasColumnName("Description2Code");

                            b1.Property<string>("GroupCode")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("nvarchar(2)")
                                .HasColumnName("GroupCode");

                            b1.Property<string>("ServiceTypeCode")
                                .IsRequired()
                                .HasMaxLength(1)
                                .HasColumnType("nvarchar(1)")
                                .HasColumnName("ServiceTypeCode");

                            b1.Property<string>("SubGroupCode")
                                .HasMaxLength(2)
                                .HasColumnType("nvarchar(2)")
                                .HasColumnName("SubGroupCode");

                            b1.HasKey("AncillaryProductId");

                            b1.ToTable("AncillaryProducts", "Ancillary");

                            b1.WithOwner()
                                .HasForeignKey("AncillaryProductId");
                        });

                    b.OwnsOne("AeroTech.Ancillary.Domain.AncillaryProductAggregate.ValueObjects.LoungeDetail", "Lounge", b1 =>
                        {
                            b1.Property<long>("AncillaryProductId")
                                .HasColumnType("bigint");

                            b1.PrimitiveCollection<string>("AirportIds")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("LoungeAirportIds");

                            b1.HasKey("AncillaryProductId");

                            b1.ToTable("AncillaryProducts", "Ancillary");

                            b1.WithOwner()
                                .HasForeignKey("AncillaryProductId");
                        });

                    b.OwnsOne("AeroTech.Ancillary.Domain.AncillaryProductAggregate.ValueObjects.QuantityPolicy", "Quantity", b1 =>
                        {
                            b1.Property<long>("AncillaryProductId")
                                .HasColumnType("bigint");

                            b1.Property<int>("Max")
                                .HasColumnType("int")
                                .HasColumnName("QuantityMax");

                            b1.Property<int>("Min")
                                .HasColumnType("int")
                                .HasColumnName("QuantityMin");

                            b1.Property<int>("Unit")
                                .HasColumnType("int")
                                .HasColumnName("QuantityUnit");

                            b1.HasKey("AncillaryProductId");

                            b1.ToTable("AncillaryProducts", "Ancillary");

                            b1.WithOwner()
                                .HasForeignKey("AncillaryProductId");
                        });

                    b.OwnsOne("AeroTech.Ancillary.Domain.AncillaryProductAggregate.ValueObjects.SalesTerms", "Terms", b1 =>
                        {
                            b1.Property<long>("AncillaryProductId")
                                .HasColumnType("bigint");

                            b1.Property<bool?>("Commissionable")
                                .HasColumnType("bit")
                                .HasColumnName("Commissionable");

                            b1.Property<string>("FormOfRefundCode")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("FormOfRefundCode");

                            b1.Property<bool?>("InterlineSettlementAllowed")
                                .HasColumnType("bit")
                                .HasColumnName("InterlineSettlementAllowed");

                            b1.Property<bool>("Refundable")
                                .HasColumnType("bit")
                                .HasColumnName("Refundable");

                            b1.Property<bool?>("Reusable")
                                .HasColumnType("bit")
                                .HasColumnName("Reusable");

                            b1.HasKey("AncillaryProductId");

                            b1.ToTable("AncillaryProducts", "Ancillary");

                            b1.WithOwner()
                                .HasForeignKey("AncillaryProductId");
                        });

                    b.Navigation("Baggage");

                    b.Navigation("Codes")
                        .IsRequired();

                    b.Navigation("Document")
                        .IsRequired();

                    b.Navigation("Lounge");

                    b.Navigation("Quantity")
                        .IsRequired();

                    b.Navigation("Terms")
                        .IsRequired();
                });

            modelBuilder.Entity("AeroTech.Ancillary.Domain.AncillaryPriceRuleAggregate.AncillaryPriceRule", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
