<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Framework\AeroTech.Framework.Presentation\AeroTech.Framework.Presentation.csproj" />
    <ProjectReference Include="..\AeroTech.Ancillary.Application\AeroTech.Ancillary.Application.csproj" />
    <ProjectReference Include="..\AeroTech.Ancillary.Synchronizer\AeroTech.Ancillary.Synchronizer.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
