<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/AeroTech.Ancillary.Application/AeroTech.Ancillary.Application.csproj" />
    <ProjectReference Include="../../src/AeroTech.Ancillary.Providers/AeroTech.Ancillary.Providers.csproj" />
    <ProjectReference Include="../../src/AeroTech.Ancillary.Persistence/AeroTech.Ancillary.Persistence.csproj" />
    <ProjectReference Include="../../src/AeroTech.Ancillary.Synchronizer/AeroTech.Ancillary.Synchronizer.csproj" />
    <ProjectReference Include="../../src/AeroTech.Ancillary.Query/AeroTech.Ancillary.Query.csproj" />
    <ProjectReference Include="../../Framework/AeroTech.Framework.Presentation/AeroTech.Framework.Presentation.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.9" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
</Project>
