// <auto-generated />
using System;
using AeroTech.Ancillary.Query._Shared.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AeroTech.Ancillary.Query.Migrations
{
    [DbContext(typeof(AncillaryQueryDbContext))]
    [Migration("20261008103947_V12Phase1NormalizedProvisionAndPricingQuery")]
    partial class V12Phase1NormalizedProvisionAndPricingQuery
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ReadModel")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryPricingAggregate.Models.AncillaryPricingLineReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int?>("AgeFromInclusive")
                        .HasColumnType("int");

                    b.Property<int?>("AgeToExclusive")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("AncillaryPricingId")
                        .HasColumnType("bigint");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PassengerTypeCode")
                        .HasColumnType("int");

                    b.Property<int?>("StationAirportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryPricingId");

                    b.ToTable("AncillaryPricingLines", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryPricingAggregate.Models.AncillaryPricingReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<int?>("FeeApplicationUnit")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("PricingUnit")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("SuspendedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId", "Status");

                    b.ToTable("AncillaryPricings", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionAirFareReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AirFareId")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionAirFares", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionAirFareTypeReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("AirFareType")
                        .HasColumnType("int");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionAirFareTypes", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionAircraftReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("AircraftId")
                        .HasColumnType("int");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionAircraft", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionBlackoutPeriodReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionBlackoutPeriods", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionCabinClassReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<int>("CabinClassId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionCabinClasses", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionCustomerReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionCustomers", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionCustomerTypeReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<int>("CustomerType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionCustomerTypes", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionDayTimeRestrictionReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("Effect")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionDayTimeRestrictions", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionDestinationAirportReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("AirportId")
                        .HasColumnType("int");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionDestinationAirports", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionFareBasisReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<string>("FareBasisCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionFareBases", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionFareFamilyReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<long>("FareFamilyId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionFareFamilies", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionFlightNumberReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionFlightNumbers", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionFlightReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<long>("FlightId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionFlights", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionMarketingAirlineReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("AirlineId")
                        .HasColumnType("int");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionMarketingAirlines", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionOperatingAirlineReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("AirlineId")
                        .HasColumnType("int");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionOperatingAirlines", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionOriginAirportReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("AirportId")
                        .HasColumnType("int");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionOriginAirports", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionPassengerTypeReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<int>("PassengerTypeCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionPassengerTypes", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionPointOfSaleReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<long>("PointOfSaleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionPointsOfSale", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionRbdReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<long>("RbdId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionRbds", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("AdvancePurchasePeriod")
                        .HasColumnType("int");

                    b.Property<int?>("AdvancePurchaseUnit")
                        .HasColumnType("int");

                    b.Property<int>("ApplicationType")
                        .HasColumnType("int");

                    b.Property<int?>("BaggageFirstExcessPiece")
                        .HasColumnType("int");

                    b.Property<int?>("BaggageFreePieces")
                        .HasColumnType("int");

                    b.Property<int?>("BaggageLastExcessPiece")
                        .HasColumnType("int");

                    b.Property<int?>("BaggagePurchaseApplication")
                        .HasColumnType("int");

                    b.Property<int?>("BaggageRuleDeference")
                        .HasColumnType("int");

                    b.Property<int?>("BaggageTravelApplication")
                        .HasColumnType("int");

                    b.Property<decimal?>("BaggageWeight")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<int?>("BaggageWeightUnit")
                        .HasColumnType("int");

                    b.Property<bool>("BookingRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("Commissionable")
                        .HasColumnType("bit");

                    b.Property<int>("CoverageScope")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Disposition")
                        .HasColumnType("int");

                    b.Property<bool>("DocumentRequired")
                        .HasColumnType("bit");

                    b.Property<int?>("FormOfRefund")
                        .HasColumnType("int");

                    b.Property<string>("FulfillmentProviderKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("InterlineSettlement")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MaxQuantity")
                        .HasColumnType("int");

                    b.Property<int>("MinQuantity")
                        .HasColumnType("int");

                    b.Property<bool>("MustCheckAvailability")
                        .HasColumnType("bit");

                    b.Property<int>("QuantityUnit")
                        .HasColumnType("int");

                    b.Property<int>("ReissueRefund")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("SalesDiscontinueAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("SalesEffectiveFrom")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<long>("ServiceDefinitionId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("SuspendedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ServiceDefinitionId", "Status");

                    b.ToTable("AncillaryProvisions", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionRoutePairReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<int>("DestinationAirportId")
                        .HasColumnType("int");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<int>("OriginAirportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionRoutePairs", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionSeasonalPeriodReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionSeasonalPeriods", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionSeatCharacteristicReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<string>("CharacteristicCode")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionSeatCharacteristics", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionSeatNumberReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionSeatNumbers", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionTravelDateReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("TravelDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionTravelDates", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionViaAirportReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("AirportId")
                        .HasColumnType("int");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionViaAirports", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryServiceDefinitionAggregate.Models.AncillaryServiceDefinitionReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("BookingMethod")
                        .HasColumnType("int");

                    b.Property<string>("BookingSsimCode")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("BookingSsrCode")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("CommercialName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description1Code")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Description2Code")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("DocumentRfic")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("DocumentRfisc")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<string>("GroupCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("OwnerAirlineId")
                        .HasColumnType("int");

                    b.Property<int?>("PricingUnit")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly?>("SalesDiscontinueOn")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("SalesEffectiveFrom")
                        .HasColumnType("date");

                    b.Property<string>("ServiceDefinitionRef")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ServiceSubCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("ServiceTypeCode")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SubCodeSource")
                        .HasColumnType("int");

                    b.Property<string>("SubGroupCode")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<long>("SupplierId")
                        .HasColumnType("bigint");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("SuspendedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.HasIndex("OwnerAirlineId", "Status");

                    b.ToTable("AncillaryServiceDefinitions", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.SupplierAggregate.Models.SupplierReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("FulfillmentKind")
                        .HasColumnType("int");

                    b.Property<string>("FulfillmentProviderKey")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OwnerAirlineId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Suppliers", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.ReferenceData.ReadModels.AirlineOfficeReadModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("AirportId")
                        .HasColumnType("int");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("LegalEntityEffectiveFrom")
                        .HasColumnType("date");

                    b.Property<long>("LegalEntityId")
                        .HasColumnType("bigint");

                    b.Property<string>("LegalEntityLegalName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long?>("OrganisationUnitId")
                        .HasColumnType("bigint");

                    b.Property<string>("OrganisationUnitName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long?>("ParentOfficeId")
                        .HasColumnType("bigint");

                    b.Property<string>("ParentOfficeName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("PointOfSaleCityId")
                        .HasColumnType("int");

                    b.Property<int?>("PointOfSaleCountryId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TimeZoneId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("AirlineOffices", "ReferenceData", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("AeroTech.Ancillary.ReferenceData.ReadModels.AirlineReadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("IataCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Airlines", "ReferenceData", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("AeroTech.Ancillary.ReferenceData.ReadModels.AirportReadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("IataCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("IkaoCode")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Airports", "ReferenceData", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("AeroTech.Ancillary.ReferenceData.ReadModels.CountryReadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alpha2Code")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Alpha3Code")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("NumericCode")
                        .HasColumnType("int");

                    b.Property<string>("PhoneCode")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Countries", "ReferenceData", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("AeroTech.Ancillary.ReferenceData.ReadModels.CurrencyReadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("DecimalPlaces")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("RoundingFactor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Currencies", "ReferenceData", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("AeroTech.Ancillary.ReferenceData.ReadModels.CustomerReadModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ClosureReasonCode")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CustomerNumber")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long?>("IndividualId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<int?>("PreferredCurrencyId")
                        .HasColumnType("int");

                    b.Property<string>("PreferredLanguageCode")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateOnly?>("RelationshipEndedOn")
                        .HasColumnType("date");

                    b.Property<DateOnly>("RelationshipStartedOn")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SuspensionReasonCode")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long?>("TravelAgencyId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Customers", "ReferenceData", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("AeroTech.Ancillary.ReferenceData.ReadModels.TravelAgencyOfficeReadModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("AirportId")
                        .HasColumnType("int");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long?>("ParentOfficeId")
                        .HasColumnType("bigint");

                    b.Property<string>("ParentOfficeName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("PointOfSaleCityId")
                        .HasColumnType("int");

                    b.Property<int?>("PointOfSaleCountryId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TimeZoneId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long>("TravelAgencyId")
                        .HasColumnType("bigint");

                    b.Property<string>("TravelAgencyLegalName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("TravelAgencyOffices", "ReferenceData", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
