// <auto-generated />
using System;
using AeroTech.Ancillary.Query._Shared.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AeroTech.Ancillary.Query.Migrations
{
    [DbContext(typeof(AncillaryQueryDbContext))]
    partial class AncillaryQueryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ReadModel")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AeroTech.Ancillary.Query.AirportSlotInventoryAggregate.Models.AirportSlotAdjustmentReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("ActorId")
                        .HasColumnType("bigint");

                    b.Property<long>("AirportSlotInventoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("ExpectedVersion")
                        .HasColumnType("bigint");

                    b.Property<int>("NewTotal")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("PreviousTotal")
                        .HasColumnType("int");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("ResultingVersion")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AirportSlotInventoryId");

                    b.ToTable("AirportSlotAdjustments", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AirportSlotInventoryAggregate.Models.AirportSlotInventoryReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("AdjustmentCount")
                        .HasColumnType("int");

                    b.Property<int>("AirportId")
                        .HasColumnType("int");

                    b.Property<int>("CapacityPersons")
                        .HasColumnType("int");

                    b.Property<bool>("ClosedForSale")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("EndUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("FacilityId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("OwnerAirlineId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OwnerAirlineId", "FacilityId", "StartUtc");

                    b.ToTable("AirportSlotInventories", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryInventoryPolicyAggregate.Models.InventoryPassengerUsageLimitReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("ConsumptionUnit")
                        .HasColumnType("int");

                    b.Property<string>("CountingFamilyCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<long>("InventoryPolicyId")
                        .HasColumnType("bigint");

                    b.Property<int>("LimitScope")
                        .HasColumnType("int");

                    b.Property<int>("MaxUnits")
                        .HasColumnType("int");

                    b.Property<decimal?>("UnitsPerPurchase")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("InventoryPolicyId");

                    b.ToTable("AncillaryInventoryPassengerUsageLimits", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryInventoryPolicyAggregate.Models.InventoryPolicyReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Authority")
                        .HasColumnType("int");

                    b.Property<int?>("CountPerAcceptedUnit")
                        .HasColumnType("int");

                    b.Property<long?>("CountResourceId")
                        .HasColumnType("bigint");

                    b.Property<int?>("CountUnit")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("LocalPattern")
                        .HasColumnType("int");

                    b.Property<int>("OwnerAirlineId")
                        .HasColumnType("int");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("ServiceDefinitionId")
                        .HasColumnType("bigint");

                    b.Property<string>("ServiceDefinitionRef")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<long?>("SlotFacilityId")
                        .HasColumnType("bigint");

                    b.Property<int?>("SlotOccupancyMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("SlotPeoplePerAcceptedUnit")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("SuspendedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<int?>("WeightConsumptionMode")
                        .HasColumnType("int");

                    b.Property<decimal?>("WeightFixedKgPerUnit")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<long?>("WeightResourceId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OwnerAirlineId", "ServiceDefinitionRef", "Status");

                    b.ToTable("AncillaryInventoryPolicies", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryPricingAggregate.Models.AncillaryPriceComponentReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.Property<long>("AncillaryPricingId")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryPricingRateId")
                        .HasColumnType("bigint");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<int?>("FeeApplicationUnit")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("StationAirportId")
                        .HasColumnType("int");

                    b.Property<bool?>("TaxIncludedInSource")
                        .HasColumnType("bit");

                    b.Property<int?>("TaxTreatment")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryPricingId");

                    b.HasIndex("AncillaryPricingRateId");

                    b.ToTable("AncillaryPriceComponents", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryPricingAggregate.Models.AncillaryPricingRateReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int?>("AgeFromInclusive")
                        .HasColumnType("int");

                    b.Property<int?>("AgeToExclusive")
                        .HasColumnType("int");

                    b.Property<long>("AncillaryPricingId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("BaseAmount")
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<int?>("PassengerTypeCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryPricingId");

                    b.ToTable("AncillaryPricingRates", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryPricingAggregate.Models.AncillaryPricingReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("PricingUnit")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("SuspendedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId", "Status");

                    b.ToTable("AncillaryPricings", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionAirFareReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AirFareId")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionAirFares", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionAirFareTypeReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("AirFareType")
                        .HasColumnType("int");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionAirFareTypes", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionAircraftReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("AircraftId")
                        .HasColumnType("int");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionAircraft", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionBlackoutPeriodReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionBlackoutPeriods", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionCabinClassReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<int>("CabinClassId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionCabinClasses", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionCoverageCountryReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionCoverageCountries", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionCustomerReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionCustomers", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionCustomerTypeReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<int>("CustomerType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionCustomerTypes", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionDayTimeWindowReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<byte>("DaysOfWeekMask")
                        .HasColumnType("tinyint");

                    b.Property<int>("Effect")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("EndLocalTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("StartLocalTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionDayTimeWindows", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionDestinationAirportReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("AirportId")
                        .HasColumnType("int");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionDestinationAirports", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionEligibleAgeBandReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("AgeFromInclusive")
                        .HasColumnType("int");

                    b.Property<int?>("AgeToExclusive")
                        .HasColumnType("int");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionEligibleAgeBands", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionFareBasisReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<string>("FareBasisCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionFareBases", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionFareFamilyReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<long>("FareFamilyId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionFareFamilies", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionFlightNumberReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionFlightNumbers", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionFlightReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<long>("FlightId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionFlights", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionMarketingAirlineReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("AirlineId")
                        .HasColumnType("int");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionMarketingAirlines", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionOperatingAirlineReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("AirlineId")
                        .HasColumnType("int");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionOperatingAirlines", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionOriginAirportReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("AirportId")
                        .HasColumnType("int");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionOriginAirports", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionPassengerTypeReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<int>("PassengerTypeCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionPassengerTypes", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionPermittedTravelPeriodReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionPermittedTravelPeriods", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionPointOfSaleReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<long>("PointOfSaleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionPointsOfSale", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionRbdReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<long>("RbdId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionRbds", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("AdvancePurchaseMaximumPeriod")
                        .HasColumnType("int");

                    b.Property<int?>("AdvancePurchasePeriod")
                        .HasColumnType("int");

                    b.Property<long?>("AdvancePurchaseRuleId")
                        .HasColumnType("bigint");

                    b.Property<bool>("AdvancePurchaseSameTimeAsTicketed")
                        .HasColumnType("bit");

                    b.Property<int?>("AdvancePurchaseUnit")
                        .HasColumnType("int");

                    b.Property<int?>("AirportServiceDirection")
                        .HasColumnType("int");

                    b.Property<long?>("AirportServiceFacilityId")
                        .HasColumnType("bigint");

                    b.Property<int?>("AirportServiceMaxGuestsPerPrimary")
                        .HasColumnType("int");

                    b.Property<long?>("AirportServiceRuleId")
                        .HasColumnType("bigint");

                    b.Property<string>("AirportServiceTerminalRef")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<TimeOnly?>("AirportServiceWindowEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("AirportServiceWindowStart")
                        .HasColumnType("time");

                    b.Property<int>("ApplicationType")
                        .HasColumnType("int");

                    b.Property<int?>("AssistedTravelConnectionPolicy")
                        .HasColumnType("int");

                    b.Property<bool?>("AssistedTravelMedicalApprovalRequired")
                        .HasColumnType("bit");

                    b.Property<int?>("AssistedTravelMinimumLeadTimeMinutes")
                        .HasColumnType("int");

                    b.Property<long?>("AssistedTravelRuleId")
                        .HasColumnType("bigint");

                    b.Property<int?>("BaggageAllowanceConcept")
                        .HasColumnType("int");

                    b.Property<long?>("BaggageApplicationRuleId")
                        .HasColumnType("bigint");

                    b.Property<int?>("BaggageChargeKind")
                        .HasColumnType("int");

                    b.Property<int?>("BaggageFirstExcessPiece")
                        .HasColumnType("int");

                    b.Property<int?>("BaggageFreePieces")
                        .HasColumnType("int");

                    b.Property<int?>("BaggageLastExcessPiece")
                        .HasColumnType("int");

                    b.Property<int?>("BaggagePurchaseApplication")
                        .HasColumnType("int");

                    b.Property<int?>("BaggageRuleDeference")
                        .HasColumnType("int");

                    b.Property<int?>("BaggageTravelApplication")
                        .HasColumnType("int");

                    b.Property<decimal?>("BaggageWeight")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<int?>("BaggageWeightUnit")
                        .HasColumnType("int");

                    b.Property<bool>("BookingRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("Commissionable")
                        .HasColumnType("bit");

                    b.Property<int>("CoverageScope")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("DayTimeApplicationRuleId")
                        .HasColumnType("bigint");

                    b.Property<int>("Disposition")
                        .HasColumnType("int");

                    b.Property<bool>("DocumentRequired")
                        .HasColumnType("bit");

                    b.Property<long?>("FareApplicationRuleId")
                        .HasColumnType("bigint");

                    b.Property<long?>("FlightApplicationRuleId")
                        .HasColumnType("bigint");

                    b.Property<int?>("FormOfRefund")
                        .HasColumnType("int");

                    b.Property<string>("FulfillmentProviderKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("GeographyRuleId")
                        .HasColumnType("bigint");

                    b.Property<bool>("InterlineSettlement")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MaxQuantity")
                        .HasColumnType("int");

                    b.Property<int>("MinQuantity")
                        .HasColumnType("int");

                    b.Property<bool>("MustCheckAvailability")
                        .HasColumnType("bit");

                    b.Property<long?>("PassengerEligibilityRuleId")
                        .HasColumnType("bigint");

                    b.Property<int?>("PetAcceptanceMode")
                        .HasColumnType("int");

                    b.Property<string>("PetCountryExceptionCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("PetMaxCombinedKgOverride")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<int?>("PetMinAnimalAgeWeeksOverride")
                        .HasColumnType("int");

                    b.Property<long?>("PetRuleId")
                        .HasColumnType("bigint");

                    b.Property<int>("PriceOrigin")
                        .HasColumnType("int");

                    b.Property<int>("PurchaseStage")
                        .HasColumnType("int");

                    b.Property<int>("QuantityUnit")
                        .HasColumnType("int");

                    b.Property<string>("QuoteProviderKey")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ReissueRefund")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("SalesDiscontinueAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("SalesEffectiveFrom")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("SalesRestrictionsRuleId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SeatApplicationRuleId")
                        .HasColumnType("bigint");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<long>("ServiceDefinitionId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("SuspendedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("TravelDateRuleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ServiceDefinitionId", "Status");

                    b.ToTable("AncillaryProvisions", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionRoutePairReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<int>("DestinationAirportId")
                        .HasColumnType("int");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<int>("OriginAirportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionRoutePairs", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionSeatCharacteristicReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<string>("CharacteristicCode")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionSeatCharacteristics", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionSeatNumberReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionSeatNumbers", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionServiceLocationReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("LocationType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionServiceLocations", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryProvisionAggregate.Models.AncillaryProvisionViaAirportReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("AirportId")
                        .HasColumnType("int");

                    b.Property<long>("AncillaryProvisionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AncillaryProvisionId");

                    b.ToTable("AncillaryProvisionViaAirports", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.AncillaryServiceDefinitionAggregate.Models.AncillaryServiceDefinitionReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("BookingConfirmationRequirement")
                        .HasColumnType("int");

                    b.Property<int>("BookingMethod")
                        .HasColumnType("int");

                    b.Property<string>("BookingSsimCode")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("BookingSsrCode")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("CommercialName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description1Code")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Description2Code")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("DocumentRfic")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("DocumentRfisc")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int?>("DocumentRouting")
                        .HasColumnType("int");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<string>("GroupCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("OwnerAirlineId")
                        .HasColumnType("int");

                    b.Property<int?>("PricingUnit")
                        .HasColumnType("int");

                    b.Property<int?>("Profile")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly?>("SalesDiscontinueOn")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("SalesEffectiveFrom")
                        .HasColumnType("date");

                    b.Property<int?>("ServiceDateBasis")
                        .HasColumnType("int");

                    b.Property<string>("ServiceDefinitionRef")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ServiceSubCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("ServiceTypeCode")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SubCodeSource")
                        .HasColumnType("int");

                    b.Property<string>("SubGroupCode")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<long>("SupplierId")
                        .HasColumnType("bigint");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("SuspendedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("VariantCode")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.HasIndex("OwnerAirlineId", "Status");

                    b.ToTable("AncillaryServiceDefinitions", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.FlightCountInventoryAggregate.Models.FlightCountAdjustmentReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("ActorId")
                        .HasColumnType("bigint");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("ExpectedVersion")
                        .HasColumnType("bigint");

                    b.Property<long>("FlightCountInventoryId")
                        .HasColumnType("bigint");

                    b.Property<int>("NewTotal")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("PreviousTotal")
                        .HasColumnType("int");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("ResultingVersion")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FlightCountInventoryId");

                    b.ToTable("FlightCountAdjustments", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.FlightCountInventoryAggregate.Models.FlightCountInventoryReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("AdjustmentCount")
                        .HasColumnType("int");

                    b.Property<bool>("ClosedForSale")
                        .HasColumnType("bit");

                    b.Property<int>("CountUnit")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("FlightId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("OwnerAirlineId")
                        .HasColumnType("int");

                    b.Property<long>("ResourceId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalCapacity")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OwnerAirlineId", "FlightId", "ResourceId");

                    b.ToTable("FlightCountInventories", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.FlightWeightInventoryAggregate.Models.FlightWeightAdjustmentReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("ActorId")
                        .HasColumnType("bigint");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("ExpectedVersion")
                        .HasColumnType("bigint");

                    b.Property<long>("FlightWeightInventoryId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("NewKg")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("PreviousKg")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("ResultingVersion")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FlightWeightInventoryId");

                    b.ToTable("FlightWeightAdjustments", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.FlightWeightInventoryAggregate.Models.FlightWeightInventoryReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("AdjustmentCount")
                        .HasColumnType("int");

                    b.Property<decimal>("CapacityKg")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<bool>("ClosedForSale")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("FlightId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("OwnerAirlineId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<long>("WeightResourceId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OwnerAirlineId", "FlightId", "WeightResourceId");

                    b.ToTable("FlightWeightInventories", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.Query.SupplierAggregate.Models.SupplierReadModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("FulfillmentKind")
                        .HasColumnType("int");

                    b.Property<string>("FulfillmentProviderKey")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OwnerAirlineId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Suppliers", "ReadModel");
                });

            modelBuilder.Entity("AeroTech.Ancillary.ReferenceData.ReadModels.AirlineOfficeReadModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("AirportId")
                        .HasColumnType("int");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("LegalEntityEffectiveFrom")
                        .HasColumnType("date");

                    b.Property<long>("LegalEntityId")
                        .HasColumnType("bigint");

                    b.Property<string>("LegalEntityLegalName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long?>("OrganisationUnitId")
                        .HasColumnType("bigint");

                    b.Property<string>("OrganisationUnitName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long?>("ParentOfficeId")
                        .HasColumnType("bigint");

                    b.Property<string>("ParentOfficeName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("PointOfSaleCityId")
                        .HasColumnType("int");

                    b.Property<int?>("PointOfSaleCountryId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TimeZoneId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("AirlineOffices", "ReferenceData", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("AeroTech.Ancillary.ReferenceData.ReadModels.AirlineReadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("IataCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Airlines", "ReferenceData", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("AeroTech.Ancillary.ReferenceData.ReadModels.AirportReadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("IataCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("IkaoCode")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Airports", "ReferenceData", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("AeroTech.Ancillary.ReferenceData.ReadModels.CountryReadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alpha2Code")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Alpha3Code")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("NumericCode")
                        .HasColumnType("int");

                    b.Property<string>("PhoneCode")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Countries", "ReferenceData", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("AeroTech.Ancillary.ReferenceData.ReadModels.CurrencyReadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("DecimalPlaces")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("RoundingFactor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Currencies", "ReferenceData", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("AeroTech.Ancillary.ReferenceData.ReadModels.CustomerReadModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ClosureReasonCode")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CustomerNumber")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long?>("IndividualId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<int?>("PreferredCurrencyId")
                        .HasColumnType("int");

                    b.Property<string>("PreferredLanguageCode")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateOnly?>("RelationshipEndedOn")
                        .HasColumnType("date");

                    b.Property<DateOnly>("RelationshipStartedOn")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SuspensionReasonCode")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long?>("TravelAgencyId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Customers", "ReferenceData", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("AeroTech.Ancillary.ReferenceData.ReadModels.TravelAgencyOfficeReadModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("AirportId")
                        .HasColumnType("int");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long?>("ParentOfficeId")
                        .HasColumnType("bigint");

                    b.Property<string>("ParentOfficeName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("PointOfSaleCityId")
                        .HasColumnType("int");

                    b.Property<int?>("PointOfSaleCountryId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TimeZoneId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long>("TravelAgencyId")
                        .HasColumnType("bigint");

                    b.Property<string>("TravelAgencyLegalName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("TravelAgencyOffices", "ReferenceData", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
